packageExtensions:
  styled-components@*:
    dependencies:
      react-is: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  fetch-blob@*:
    dependencies:
      stream: "*"
  mongodb@*:
    dependencies:
      bson-ext: "*"
      kerberos: "*"
      snappy: "*"
      aws4: "*"
      mongodb-client-encryption: "*"
      stream: "*"
  "@storybook/react@*":
    dependencies:
      "@storybook/builder-webpack5": "*"
      "@storybook/manager-webpack5": "*"
nodeLinker: "node-modules"
