nodeLinker: node-modules

packageExtensions:
  "@storybook/react@*":
    dependencies:
      "@storybook/builder-webpack5": "*"
      "@storybook/manager-webpack5": "*"
  debug@*:
    dependencies:
      supports-color: "*"
  fetch-blob@*:
    dependencies:
      stream: "*"
  mongodb@*:
    dependencies:
      aws4: "*"
      bson-ext: "*"
      kerberos: "*"
      mongodb-client-encryption: "*"
      snappy: "*"
      stream: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
