// This file is autogenerated do not modify manually
export const constants = {
  colors: {
    colorWhite: "#d0dcd6",
    colorGray: "#e8edde",
    colorYellow: "#f5cc5c",
    colorBlack: "#242423",
    colorGrayDark: "#323432",
    colorRed: "#c50239",
    colorBody: "#242423",
    colorText: "#e8edde",
    colorHeader: "#f5cc5c"
  }
};
